[235] Flatten database migrations (#198)
### Context

Ticket:
https://github.com/DFE-Digital/teacher-training-entitlement-board/issues/235

Refactoring has broken the database migrations and we can't deploy to
review apps, eg.

```
Caused by:
NameError: uninitialized constant LeadProvider::ALL_ACTIVE_PROVIDERS (NameError)

    school_led_network_lead_provider = LeadProvider.find_by(ecf_id: LeadProvider::ALL_ACTIVE_PROVIDERS["School-Led Network"])
                                                                                ^^^^^^^^^^^^^^^^^^^^^^
/app/db/migrate/20221130142333_add_hint_to_lead_providers.rb:5:in 'AddHintToLeadProviders#up'
Tasks: TOP => db:migrate
```

### Changes proposed in this pull request

Archive all migrations.

---------

Co-authored-by: Ben Keeping <benjaminkeeping@gmail.com>